# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\views\qt_windows\connect_to_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_connect_to_db(object):
    def setupUi(self, form_connect_to_db):
        form_connect_to_db.setObjectName("form_connect_to_db")
        form_connect_to_db.resize(647, 289)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\views\\qt_windows\\../ico_gui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form_connect_to_db.setWindowIcon(icon)
        self.parameters_combo_box = QtWidgets.QGroupBox(form_connect_to_db)
        self.parameters_combo_box.setGeometry(QtCore.QRect(0, 0, 641, 241))
        self.parameters_combo_box.setObjectName("parameters_combo_box")
        self.parameters_fault_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_fault_label.setEnabled(False)
        self.parameters_fault_label.setGeometry(QtCore.QRect(470, 60, 55, 16))
        self.parameters_fault_label.setObjectName("parameters_fault_label")
        self.parameters_check_save_parametrs = QtWidgets.QCheckBox(self.parameters_combo_box)
        self.parameters_check_save_parametrs.setGeometry(QtCore.QRect(20, 190, 161, 20))
        self.parameters_check_save_parametrs.setObjectName("parameters_check_save_parametrs")
        self.parameters_host_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_host_label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.parameters_host_label.setObjectName("parameters_host_label")
        self.parameters_name_db_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_name_db_label.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.parameters_name_db_label.setObjectName("parameters_name_db_label")
        self.parameters_user_name_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_user_name_label.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.parameters_user_name_label.setObjectName("parameters_user_name_label")
        self.parameters_password_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_password_label.setGeometry(QtCore.QRect(20, 150, 55, 16))
        self.parameters_password_label.setObjectName("parameters_password_label")
        self.parameters_port_label = QtWidgets.QLabel(self.parameters_combo_box)
        self.parameters_port_label.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.parameters_port_label.setObjectName("parameters_port_label")
        self.parameters_host_text = QtWidgets.QLineEdit(self.parameters_combo_box)
        self.parameters_host_text.setGeometry(QtCore.QRect(140, 30, 301, 22))
        self.parameters_host_text.setObjectName("parameters_host_text")
        self.parameters_port_text = QtWidgets.QLineEdit(self.parameters_combo_box)
        self.parameters_port_text.setGeometry(QtCore.QRect(140, 60, 301, 22))
        self.parameters_port_text.setObjectName("parameters_port_text")
        self.parameters_name_db_text = QtWidgets.QLineEdit(self.parameters_combo_box)
        self.parameters_name_db_text.setGeometry(QtCore.QRect(140, 90, 301, 22))
        self.parameters_name_db_text.setObjectName("parameters_name_db_text")
        self.parameters_user_name_text = QtWidgets.QLineEdit(self.parameters_combo_box)
        self.parameters_user_name_text.setGeometry(QtCore.QRect(140, 120, 301, 22))
        self.parameters_user_name_text.setObjectName("parameters_user_name_text")
        self.parameters_password_text = QtWidgets.QLineEdit(self.parameters_combo_box)
        self.parameters_password_text.setGeometry(QtCore.QRect(140, 150, 301, 22))
        self.parameters_password_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.parameters_password_text.setPlaceholderText("")
        self.parameters_password_text.setObjectName("parameters_password_text")
        self.parameters_check_default_connect_settings = QtWidgets.QCheckBox(self.parameters_combo_box)
        self.parameters_check_default_connect_settings.setGeometry(QtCore.QRect(210, 190, 391, 20))
        self.parameters_check_default_connect_settings.setObjectName("parameters_check_default_connect_settings")
        self.connect_to_db_button = QtWidgets.QPushButton(form_connect_to_db)
        self.connect_to_db_button.setGeometry(QtCore.QRect(402, 250, 111, 28))
        self.connect_to_db_button.setObjectName("connect_to_db_button")
        self.cancel_connect_to_db_button = QtWidgets.QPushButton(form_connect_to_db)
        self.cancel_connect_to_db_button.setGeometry(QtCore.QRect(530, 250, 93, 28))
        self.cancel_connect_to_db_button.setObjectName("cancel_connect_to_db_button")

        self.retranslateUi(form_connect_to_db)
        QtCore.QMetaObject.connectSlotsByName(form_connect_to_db)

    def retranslateUi(self, form_connect_to_db):
        _translate = QtCore.QCoreApplication.translate
        form_connect_to_db.setWindowTitle(_translate("form_connect_to_db", "Connect to database"))
        self.parameters_combo_box.setTitle(_translate("form_connect_to_db", "Параметры"))
        self.parameters_fault_label.setText(_translate("form_connect_to_db", "ОШИБКА"))
        self.parameters_check_save_parametrs.setText(_translate("form_connect_to_db", "Сохранить параметры"))
        self.parameters_host_label.setText(_translate("form_connect_to_db", "Хост:"))
        self.parameters_name_db_label.setText(_translate("form_connect_to_db", "База данных:"))
        self.parameters_user_name_label.setText(_translate("form_connect_to_db", "Пользователь:"))
        self.parameters_password_label.setText(_translate("form_connect_to_db", "Пароль:"))
        self.parameters_port_label.setText(_translate("form_connect_to_db", "Порт:"))
        self.parameters_check_default_connect_settings.setText(_translate("form_connect_to_db", "Тестовые параметры подключения (по умолчанию posgress)"))
        self.connect_to_db_button.setText(_translate("form_connect_to_db", "Подключиться"))
        self.cancel_connect_to_db_button.setText(_translate("form_connect_to_db", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_connect_to_db = QtWidgets.QDialog()
    ui = Ui_form_connect_to_db()
    ui.setupUi(form_connect_to_db)
    form_connect_to_db.show()
    sys.exit(app.exec_())
